### ISSUE TITLE
remove parent level package-lock.json?

### ISSUE THREAD

**Issue by mixelpixel** [LambdaSchool/Sprint-Challenge---React#90]
Students should be able to figure out to `cd starwars` before they `npm i` but is this file needed? If not, can we remove it?

**Comment by ryanhca** [comment]
Definetley not important. NPM says to keep lock files in readmes but more in a team environment.

**Comment by ryanhca** [comment]
Go ahead and remove and submit a PR. :)

**Comment by mixelpixel** [comment]
:+1:
